<a href="https://colab.research.google.com/github/mcd-unison/material-programacion/blob/main/intro-python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>
<p><img src="https://mcd.unison.mx/wp-content/themes/awaken/img/logo_mcd.png" width="100">
</p>



# Curso Propedéutico en *Programación*

## Introducción a `python` resolviendo preguntas


**Julio Waissman Vilanova**



### Tipos

¿Cuales son los tipos de datos básicos? Revisa los tipos siguientes:

1. Tipos numéricos `int`, `float`, `complex`
2. Cadenas de caracteres
3. Tuplas
4. Listas
5. Diccionarios
6. Conjuntos

Da ejemplo de sobrecarga de operadores (en particular `+` y `*`)



In [ ]:
# SOBRECARGA DE OPERADORES
a = "Hola"
b = 'Adiós'
c = 6
d= 3.141592654
print (a + b)
print (c + d)
print (a * 3)
print (c * 3)

HolaAdiós
9.141592654
HolaHolaHola
18


¿Que significa que unos tipos sean *mutables* y otros *inmutables*?

Realiza un pequeño programa donde quede claro lo que significa que un tipo de datos sea mutable, e ilustra el uso del método `copy.deepcopy()`.

In [ ]:
# Ejemplo de datos mutables
l = [2,3.14, b, [2,5,8]]
lista = l
l.append(5) #Agrega el elemento 5 a la lista
print(lista)

[2, 3.14, 'Adiós', [2, 5, 8], 5]


In [ ]:
# Uso del método copy.deepcopy()
import copy
l2 = copy.deepcopy(l)
l2.append(6)
print(f'La lista original es: {l}\n')
print(f'La lista original usando copy.deepcopy es:{l2}')

La lista original es: [2, 3.14, 'Adiós', [2, 5, 8], 5]

La lista original usando copy.deepcopy es:[2, 3.14, 'Adiós', [2, 5, 8], 5, 6]


### *Comprehension* de listas, conjuntos y diccionarios

Escribe, en una sola linea, una expresión que genere una lista con todos los números enteros que se encuentran entre $1$ y $n$
que sean divisibles por $3$ y $7$ y que el dígito menos significativo del número sea $6$.

In [ ]:
n = 10_000

# Escribe aqui el *one linner*

lista = {x:
x for x in range(1, n+1)
if x % 3 == 0 and x % 7 == 0 and x % 10 == 6
}
print(lista.keys())

dict_keys([126, 336, 546, 756, 966, 1176, 1386, 1596, 1806, 2016, 2226, 2436, 2646, 2856, 3066, 3276, 3486, 3696, 3906, 4116, 4326, 4536, 4746, 4956, 5166, 5376, 5586, 5796, 6006, 6216, 6426, 6636, 6846, 7056, 7266, 7476, 7686, 7896, 8106, 8316, 8526, 8736, 8946, 9156, 9366, 9576, 9786, 9996])


### Funciones

Escribe una función que:

1. reciba una lista de elementos (letras, números, lo que sea),
2. cuente la ocurrencia de cada elemento en la lista,
3. devuelva las ocurrencias en forma de diccionario,
4. si imprime es True, imprima un histograma de ocurrencias, por ejemplo:

```python

lista = [1,'a',1, 13, 'hola', 'a', 1, 1, 'a', 1]

d = funcion_ejemplo(lista, imprime = True)

1    		***** 	(5 -> 50%)
'a'  		***   	(3 -> 30%)
13		*	(1 -> 10%)
'hola'		*	(1 -> 10%)

```

In [ ]:
# Escribe la función aquí

def funcion_ejemplo(listas, imprime=False):
  h = {x : listas.count(x) for x in set(lista)}
  if imprime==True:
    for key, val in h.items():
      print(f"{key}\t\t{val * '*'}\t\t({val} --> {val / len(lista): .2%})")
  return h

In [ ]:
# Realiza pruebas aquí
lista = [1,'a',1, 13, 'hola', 'a', 1, 1, 'a', 1]
d = funcion_ejemplo(lista, imprime = True)
print(d)

1		*****		(5 -->  50.00%)
13		*		(1 -->  10.00%)
a		***		(3 -->  30.00%)
hola		*		(1 -->  10.00%)
{1: 5, 13: 1, 'a': 3, 'hola': 1}


Escribe una función que modifique un diccionario y regrese el diccionario modificado y una copia del original, donde cada entrada
del diccionario sea una lista de valores. Ten en cuenta que si una entrada del diccionario es de tipo mutable, al modificarlo en la
copia se modifica el original. Utiliza el modulo `copy` para evitar este problema. Ejemplo de la función:

```python
dic1 = {'Pepe':[12, 'enero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}
dic2 = fundicos(dic1, 'Pepe', 1, 'febrero')

print(dic1)
{'Pepe':[12, 'enero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}

print(dic2)
{'Pepe':[12, 'febrero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}
```

In [ ]:
import copy
# Escribe la función aquí
def fundicos(diccionario, llave, valor1, valor2):
  copy_dic = copy.deepcopy(diccionario)
  copy_dic[llave][0] = valor1
  copy_dic[llave][1] = valor2
  return copy_dic

In [ ]:
# Realiza pruebas de fundicos aquí
dic1 = {'Pepe':[12, 'enero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}
dic2 = fundicos(dic1,'Pepe', 1, 'febrero')

print(dic1)
print(dic2)

{'Pepe': [12, 'enero', 1980], 'Carolina': [15, 'mayo', 1975], 'Paco': [10, 'nov', 1970]}
{'Pepe': [1, 'febrero', 1980], 'Carolina': [15, 'mayo', 1975], 'Paco': [10, 'nov', 1970]}


### Generadores

Escribe un generador que reciba una lista y genere todas las permutaciones que se puedan hacer con los elementos de la lista

In [ ]:
# Escribe aqui fun1

def permutaciones(lista):
    """
    Permutaciones de los elementos de una lista.

    Devuelve un generador con todas las permutaciones posibles de los elementos de la lista de entrada
    """
    #TODO: Implementar la función

In [ ]:
# Realiza pruebas de fun2 aquí
for p in permutaciones(['a', 'b', 'c', 'd']):
    print(p)

Ahora escribe una funcipn que reciba 4 digitos del 0 al 9, y devuelva una lista con todas las horas váidas que se puedan hacer con estos dígitos en forma de lista de strings con la forma `"HH:MM"`.

In [ ]:
def horas_validas(lista):
    """
    Recibe una lista de 4 dígitos y devuelve una lista con todas las horas válidas que se pueden hacer con estos dígitos en forma de lista de strings con la forma "HH:MM".

    Args:
    lista: Una lista de 4 dígitos del 0 al 9.

    Returns:
    Una lista de strings con las horas válidas en formato "HH:MM".
    """
    horas = []

    for h1 in lista:
        for h2 in lista:
            h = h1 * 10 + h2
            if h < 24:
                for m1 in lista:
                    for m2 in lista:
                        m = m1 * 10 + m2
                        if m < 60:
                            horas.append(f"{h:02d}:{m:02d}")
    return horas

Validando:

In [ ]:
print(horas_validas([1,2,3,7]))

['11:11', '11:12', '11:13', '11:17', '11:21', '11:22', '11:23', '11:27', '11:31', '11:32', '11:33', '11:37', '12:11', '12:12', '12:13', '12:17', '12:21', '12:22', '12:23', '12:27', '12:31', '12:32', '12:33', '12:37', '13:11', '13:12', '13:13', '13:17', '13:21', '13:22', '13:23', '13:27', '13:31', '13:32', '13:33', '13:37', '17:11', '17:12', '17:13', '17:17', '17:21', '17:22', '17:23', '17:27', '17:31', '17:32', '17:33', '17:37', '21:11', '21:12', '21:13', '21:17', '21:21', '21:22', '21:23', '21:27', '21:31', '21:32', '21:33', '21:37', '22:11', '22:12', '22:13', '22:17', '22:21', '22:22', '22:23', '22:27', '22:31', '22:32', '22:33', '22:37', '23:11', '23:12', '23:13', '23:17', '23:21', '23:22', '23:23', '23:27', '23:31', '23:32', '23:33', '23:37']


Escribe una función, lo más compacta posible, que escoja entre los 3 patrones a continuación, e imprima en pantalla
el deseado, pero de dimensión $n$ ($n \ge 4$), toma en cuanta que para algunos valores de $n$ habrá
algún(os) patrones que no se puedan hacer.

```
          *             ++++           oooooooo
          **            ++++           ooo  ooo
          ***           ++++           oo    oo
          ****          ++++           o      o
          *****             ++++       o      o
          ******            ++++       oo    oo
          *******           ++++       ooo  ooo
          ********          ++++       oooooooo

```

In [277]:
def imprimir_patron(patron, n):
    if n < 4:
        print("El tamaño mínimo es 4.") #para que pueda realizar los patrones
        return

    if patron == 1:
        for i in range(1, n+1):
            print('*' * i)
    elif patron == 2: # válido solo si n es par
        if n % 2 != 0:
            print("Para este patrón, n debe ser par.")
            return
        m = n // 2
        for _ in range(m):
            print('+' * m + ' ' * m) #Realiza el dibujo centrado a la izq.
        for _ in range(m):
            print(' ' * m + '+' * m) #Realiza el dibujo centrado a la der.
    elif patron == 3: # para este patrón me apoye de chatgpt
        if n % 2 != 0: # n debe ser par para poder realizar el patrón
            print("Para este patrón, n debe ser par.")
            return
        m = n // 2
        print('o' * n) # Para la primera fila
        for i in range(m-1):
            print('o' * (m - i - 1) + ' ' * (2 * (i + 1)) + 'o' * (m - i - 1))
        print('o' + ' ' * (n - 2) + 'o') #fila de enmedio
        for i in range(m - 2):
            print('o' * (i + 2) + ' ' * (n - 2 * (i + 2)) + 'o' * (i + 2))
        print('o' * n) #ultima fila
    else:
        print("Patrón no reconocido. Usa 1, 2 o 3.")

In [275]:
#Realiza pruebas aquí
imprimir_patron(3, 10)  # La primera entrada es el patrón elegido, y la segunda es n

oooooooooo
oooo  oooo
ooo    ooo
oo      oo
o        o
o        o
oo      oo
ooo    ooo
oooo  oooo
oooooooooo


In [278]:
imprimir_patron(1, 5)

*
**
***
****
*****


In [279]:
imprimir_patron(2, 5)

Para este patrón, n debe ser par.


### Clases y objetos

Diseña una clase Matriz con las siguientes características:

1. Como inicialización de un objeto es necesario conocer $n$, $m$ y tipo. En caso de no proporcionar $m$ la matriz se asume cuadrada de $n \times n$. En caso de no proporcionar $n$ la matriz tendrá una dimensión de $1 \times 1$.
2. De no especificarse todos los elementos se inicializan a 0, a menos que exista un tipo especial ( `unos` o `diag` por el momento).
3. Implementa con sobrecarga la suma de matrices, la multiplicación de matrices y la multiplicación por un escalar.
4. Implementa como métodos eliminar columna y eliminar fila.   
5. Programa la representación visual de la matriz.
6. Ten en cuenta tambien el manejo de errores.


Ejemplo de uso:

```
>>> A = Matriz(n=3, m=4)

>>> print(A)
0 0 0 0
0 0 0 0
0 0 0 0

>>> A = A.quitafila(2)

>>> print(A)
0 0 0 0
0 0 0 0

>>> B = Matriz(4,4,'diag')

>>> print(B)
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1

>>> C = Matriz(4,1,'unos')

>>> print(C)
1
1
1
1

>>> D = 3 * B * C

>>> print(D)
3
3
3
3

>>> E = 3 * B + C
error "No seas menso, si no son de la misma dimensión las matrices no se pueden sumar"
```

In [271]:
# Desarrolla aqui la clase
class Matriz:
  def __init__(self, tipo=None, n=1, m=None):
      if tipo not in [None, 'unos', 'diag']:
          raise ValueError("El tipo de matriz no es válido.")
      if n < 1 or (m is not None and m < 1):
          raise ValueError("Las dimensiones de la matriz deben ser positivas.")

      self.n = n #renglones
      self.m = m if m is not None else n #columnas
      self.tipo = tipo #si es de unos o ceros
      if tipo == 'unos':
          self.matriz = [[1]*self.m for _ in range(self.n)]
      elif tipo == 'diag':
          self.matriz = [[1 if i == j else 0 for j in range(self.m)] for i in range(self.n)]
      else:
          self.matriz = [[0]*self.m for _ in range(self.n)]

  def __str__(self):
      return '\n'.join([' '.join(map(str, fila)) for fila in self.matriz])

  def add(self, B):
      if self.n != B.n or self.m != B.m:
          raise ValueError("Las matrices deben tener la misma dimensión.")
      suma = Matriz(None, self.n, self.m)
      suma.matriz = [[self.matriz[i][j] + B.matriz[i][j] for j in range(self.m)] for i in range(self.n)]
      return suma

  def mult(self, B):
      if self.m != B.n:
          raise ValueError('Las matrices no se pueden multiplicar')
      result = Matriz(None, self.n, B.m)
      sum = __builtins__.sum
      result.matriz = [[sum(self.matriz[i][k] * B.matriz[k][j] for k in range(self.m)) for j in range(B.m)] for i in range(self.n)]
      return result

  def multesc(self, a):
      mult = Matriz(None, self.n, self.m)
      mult.matriz = [[self.matriz[i][j] * a for j in range(self.m)] for i in range(self.n)]
      return mult

  def elimina(self, cof, indice):
      if cof == 'columna':
          if indice < 0 or indice >= self.m:
              raise ValueError("La columna especificada está fuera de los límites de la matriz.")
          for i in range(self.n):
              del self.matriz[i][indice]
          self.m -= 1
      elif cof == 'fila':
          if indice < 0 or indice >= self.n:
              raise ValueError("La fila especificada está fuera de los límites de la matriz.")
          del self.matriz[indice]
          self.n -= 1
      else:
          raise IndexError("Índice de fila fuera de rango")
      return self

In [270]:
# Check if 'sum' has been overwritten
print(sum)

# If it prints 'None', reset it to the built-in function
sum = __builtins__.sum

# Now try your multiplication again
A = Matriz('unos',3,3)
B = Matriz('diag',3,3)
c = A.mult(B)
print(c)

None
1 1 1
1 1 1
1 1 1


In [272]:
# Realiza las pruebas a la clase aquí
A = Matriz(None, n=3, m=4)
print(f'A =\n{A}')

AM = A.elimina('fila',2)
print(f'A =\n{AM}')

B = Matriz('diag', 4,4)
print(f'B =\n{B}')

C = Matriz('unos',4,1)
print(f'C =\n{C}')

D = (B.multesc(3)).mult(C)
print(f'D =\n{D}')

E = (B.multesc(3)).add(C)
print(f'E =\n{E}')

A =
0 0 0 0
0 0 0 0
0 0 0 0
A =
0 0 0 0
0 0 0 0
B =
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1
C =
1
1
1
1
D =
3
3
3
3


ValueError: Las matrices deben tener la misma dimensión.